Repository DLStahl/CapstoneRemodel, pull requests merged in 2021-04, with the labels that each got.

#30 Move Models pt 2
  laravel/database/seeds/TaskAbbreviationSeeder.php
  laravel/tests/Feature/evaluationsTest.php
  laravel/tests/Unit/AdminAddDataSetTest.php
  laravel/tests/Unit/AdminAddUpdateMilestoneTest.php
  laravel/tests/Unit/AdminAddUserTest.php
  laravel/tests/Unit/AdminDeleteDataSetTest.php
  laravel/tests/Unit/AdminEvalButtonTest.php
  laravel/tests/Unit/AutoAssignmentTest.php
  laravel/tests/Unit/EvaluateGenerateTimeIntervalsTest.php
  laravel/tests/Unit/EvaluationParserTest.php
  laravel/tests/Unit/FilterByRotationTest.php
  laravel/tests/Unit/GenerateSendNotificationForOverwriteTest.php
  laravel/tests/Unit/GenerateUserNotFoundNotificationTest.php
  laravel/tests/Unit/InitiateEvalTest.php
  laravel/tests/Unit/MapRotationEvaluationTest.php
  laravel/tests/Unit/MedHubAPIAvailableTest.php
  laravel/tests/Unit/ParseEpicCSVTest.php
  laravel/tests/Unit/ResidentConfirmationFlowTest.php
  laravel/tests/Unit/ResidentConfirmationPageTest.php
  laravel/tests/Unit/ResidentFillsLearningObjectiveTest.php
  laravel/tests/Unit/ResidentMySelectionPageTest.php
  laravel/tests/Unit/ResidentScheduleFilterTest.php
  laravel/tests/Unit/ResidentSelectDayTest.php
  laravel/tests/Unit/ResidentSelectMilestoneTest.php
  laravel/tests/Unit/ResidentSubmitPreferenceTest.php
  laravel/tests/Unit/ResidentSubmitsFromOneScreenTest.php
  laravel/tests/Unit/ResidentSubmitsSelectionTextTest.php
  laravel/tests/Unit/ResidentViewPreferencesTest.php
  laravel/tests/Unit/ResidentViewTableTest.php
  laravel/tests/Unit/RetrieveResidentIDTest.php
  laravel/tests/Unit/RetrieveScheduleRotationTest.php
  laravel/tests/Unit/SaveMedHubInfoTest.php
  laravel/tests/Unit/ScheduleDataTableTest.php
  laravel/tests/Unit/ScheduleFileExistsandIsTxtTest.php
  laravel/tests/Unit/SendEvalTest.php
  laravel/tests/Unit/SendEvaluations.php
  laravel/tests/Unit/SendNotificationTest.php
  laravel/tests/Unit/TableTest.php
  laravel/tests/Unit/TabletPhoneTest.php
  laravel/tests/Unit/UpdateAnesthesiologistsDataTest.php
  laravel/tests/Unit/UpdateParsedDataTest.php
  laravel/tests/Unit/UpdateResidentPageListingTest.php
Labels: bug

#35 fix psr-4 test name errors
  laravel/tests/Unit/EvaluateGenerateTimeIntervalsTest.php
  laravel/tests/Unit/GenerateSendNotificationForOverwriteTest.php
  laravel/tests/Unit/MapRotationEvaluationTest.php
  laravel/tests/Unit/ResidentFillsLearningObjectiveTest.php
  laravel/tests/Unit/ResidentSelectDayTest.php
  laravel/tests/Unit/ResidentSelectMilestoneTest.php
  laravel/tests/Unit/ResidentSubmitPreferenceTest.php
  laravel/tests/Unit/ResidentSubmitsFromOneScreenTest.php
  laravel/tests/Unit/ResidentSubmitsSelectionTextTest.php
  laravel/tests/Unit/ResidentViewPreferencesTest.php
  laravel/tests/Unit/ResidentViewTableTest.php
  laravel/tests/Unit/RetrieveScheduleRotationTest.php
  laravel/tests/Unit/SaveMedHubInfoTest.php
  laravel/tests/Unit/ScheduleDataTableTest.php
  laravel/tests/Unit/ScheduleFileExistsandIsTxtTest.php
  laravel/tests/Unit/SendEvalTest.php
  laravel/tests/Unit/TableTest.php
  laravel/tests/Unit/TabletPhoneTest.php
Labels: bug, enhancement

#28 Upgrade Laravel to 6.0
  .gitignore
  laravel/composer.json
  laravel/composer.lock
  laravel/config/cache.php
  laravel/config/session.php
  laravel/phpunit.xml
  laravel/public/svg/403.svg
  laravel/public/svg/404.svg
  laravel/public/svg/500.svg
  laravel/public/svg/503.svg
  laravel/storage/framework/cache/.gitignore
  laravel/storage/framework/cache/data/.gitignore
Labels: enhancement

#40 Cleanup seeders
  laravel/database/seeds/DatabaseSeeder.php
  laravel/database/seeds/EvaluationFormsTableSeeder.php
  laravel/database/seeds/FilterRotationTableSeeder.php
  laravel/database/seeds/MilestoneTableSeeder.php
Labels: enhancement

#45 fix PushSchedule bug
  laravel/app/Console/Commands/PushSchedule.php
Labels: bug

#43 upgrade to laravel 8
  laravel/.editorconfig
  laravel/.gitignore
  laravel/README.md
  laravel/app/Console/Commands/InitiateEval.php
  laravel/app/Exceptions/Handler.php
  laravel/app/Http/Controllers/Auth/ForgotPasswordController.php
  laravel/app/Http/Controllers/Auth/LoginController.php
  laravel/app/Http/Controllers/Auth/RegisterController.php
  laravel/app/Http/Controllers/Auth/ResetPasswordController.php
  laravel/app/Http/Controllers/Controller.php
  laravel/app/Http/Controllers/PagesController.php
  laravel/app/Http/Kernel.php
  laravel/app/Http/Middleware/Authenticate.php
  laravel/app/Http/Middleware/PreventRequestsDuringMaintenance.php
  laravel/app/Http/Middleware/RedirectIfAuthenticated.php
  laravel/app/Http/Middleware/TrimStrings.php
  laravel/app/Http/Middleware/TrustHosts.php
  laravel/app/Http/Middleware/TrustProxies.php
  laravel/app/Models/User.php
  laravel/app/Providers/AppServiceProvider.php
  laravel/app/Providers/AuthServiceProvider.php
  laravel/app/Providers/BroadcastServiceProvider.php
  laravel/app/Providers/EventServiceProvider.php
  laravel/app/Providers/RouteServiceProvider.php
  laravel/bootstrap/app.php
  laravel/composer.json
  laravel/composer.lock
  laravel/config/app.php
  laravel/config/cors.php
  laravel/config/session.php
  laravel/database/.gitignore
  laravel/database/factories/UserFactory.php
  laravel/database/seeders/DatabaseSeeder.php
  laravel/database/seeders/EvaluationFormsTableSeeder.php
  laravel/database/seeders/FilterRotationTableSeeder.php
  laravel/database/seeders/MilestoneTableSeeder.php
  laravel/database/seeders/ScheduleDataStaticSeeder.php
  laravel/database/seeders/TaskAbbreviationSeeder.php
  laravel/package.json
  laravel/phpunit.xml
  laravel/public/.htaccess
  laravel/public/index.php
  laravel/public/web.config
  laravel/readme.md
  laravel/resources/assets/js/components/ExampleComponent.vue
  laravel/resources/js/app.js
  laravel/resources/js/bootstrap.js
  laravel/resources/sass/_variables.scss
  laravel/resources/sass/app.scss
  laravel/routes/api.php
  laravel/routes/channels.php
  laravel/routes/console.php
  laravel/routes/web.php
  laravel/server.php
  laravel/tests/Feature/EvaluationsTest.php
  laravel/webpack.mix.js
Labels: dependencies, enhancement

#47 hotfix laravel bug
  laravel/app/Http/Kernel.php
Labels: bug

#49 misc cleanup cj
  laravel/app/Console/Commands/PushSchedule.php
  laravel/resources/views/pages/about.blade.php
  laravel/resources/views/schedules/admin/milestones.blade.php
  laravel/resources/views/schedules/admin/milestones_confirm.blade.php
Labels: enhancement

#50 More Cleanup
  .gitattributes
  laravel/app/Console/Commands/InitiateEval.php
  laravel/app/Console/Commands/PushSchedule.php
  laravel/app/Console/Commands/UpdateEvaluateData.php
  laravel/app/EvaluationParser.php
  laravel/app/Http/Controllers/MedhubController.php
  laravel/app/Http/Controllers/PagesController.php
  laravel/app/Http/Controllers/ScheduleDataController.php
  laravel/app/Models/Attending.php
  laravel/app/Models/EvaluateData.php
  laravel/app/Models/Resident.php
  laravel/app/ScheduleParser.php
  laravel/config/mail.php
  laravel/database/migrations/2021_04_06_152448_add_is_valid_column_to_option.php
  laravel/database/migrations/2021_04_06_160224_create_rotations_table.php
  laravel/resources/views/emails/mail_table.blade.php
  laravel/resources/views/pages/about.blade.php
  laravel/resources/views/schedules/admin/deleteDB.blade.php
  laravel/resources/views/schedules/admin/milestones.blade.php
  laravel/resources/views/schedules/admin/milestones_confirm.blade.php
  laravel/resources/views/schedules/resident/milestone.blade.php
  laravel/routes/web.php
  laravel/tests/Feature/EvaluationsTest.php
  laravel/tests/Unit/AdminAddDataSetTest.php
  laravel/tests/Unit/AdminAddUpdateMilestoneTest.php
  laravel/tests/Unit/AdminAddUserTest.php
  laravel/tests/Unit/AdminControllerTest.php
  laravel/tests/Unit/AdminDeleteDataSetTest.php
  laravel/tests/Unit/AdminEvalButtonTest.php
  laravel/tests/Unit/AutoAssignmentTest.php
  laravel/tests/Unit/EvaluateGenerateTimeIntervalsTest.php
  laravel/tests/Unit/EvaluationParserTest.php
  laravel/tests/Unit/FilterByRotationTest.php
  laravel/tests/Unit/GenerateSendNotificationForOverwriteTest.php
  laravel/tests/Unit/GenerateUserNotFoundNotificationTest.php
  laravel/tests/Unit/InitiateEvalTest.php
  laravel/tests/Unit/MapRotationEvaluationTest.php
  laravel/tests/Unit/MedHubAPIAvailableTest.php
  laravel/tests/Unit/MedhubControllerTest.php
  laravel/tests/Unit/ParseEpicCSVTest.php
  laravel/tests/Unit/ResidentFillsLearningObjectiveTest.php
  laravel/tests/Unit/ResidentSelectMilestoneTest.php
  laravel/tests/Unit/ResidentSubmitsFromOneScreenTest.php
  laravel/tests/Unit/ResidentSubmitsSelectionTextTest.php
  laravel/tests/Unit/ResidentViewPreferencesTest.php
  laravel/tests/Unit/ResidentViewTableTest.php
  laravel/tests/Unit/RetrieveResidentIDTest.php
  laravel/tests/Unit/RetrieveScheduleRotationTest.php
  laravel/tests/Unit/SaveMedHubInfoTest.php
  laravel/tests/Unit/ScheduleDataTableTest.php
  laravel/tests/Unit/ScheduleFileExistsandIsTxtTest.php
  laravel/tests/Unit/ScheduleParserTest.php
  laravel/tests/Unit/SendEvaluations.php
  laravel/tests/Unit/SendNotificationTest.php
  laravel/tests/Unit/TableTest.php
  laravel/tests/Unit/UpdateAnesthesiologistsDataTest.php
  laravel/tests/Unit/UpdateParsedDataTest.php
  laravel/tests/Unit/UpdateResidentPageListingTest.php
Labels: enhancement

#52 update readme
  README.md
Labels: documentation, enhancement
